### ISSUE TITLE
ruby: produces BigDecimal deprecation warning in ruby 2.6

### ISSUE THREAD

**Issue by jrochkind** [softdevteam/libkalibera#5]
ruby/2.6.6/gems/kalibera-0.1/lib/kalibera/data.rb:92: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

kalibera gem version 0.1, the only release I think.

**Comment by jrochkind** [comment]
Looks like this is already fixed in master, in fact two years ago!

https://github.com/softdevteam/libkalibera/commit/fefdcd09e93233cd99e00cd4e2896fe804b64206

Is it possible to get a rubygems release off current master, so it's easy to use the latest version of the code with this and other fixes? I'd recommend releasing `1.0`, since this gem is fairly widely used (as a result of being depended on/recommended by the [benchmark-ips](https://github.com/evanphx/benchmark-ips))

**Comment by ltratt** [comment]
I'm afraid I know nothing about releasing Ruby gems :/ @chrisseaton kindly did the Ruby support, so he might have an opinion?

**Comment by chrisseaton** [comment]
I'll take a look soon.

**Comment by ltratt** [comment]
Thanks Chris!

**Comment by chrisseaton** [comment]
Available as `0.1.1`.
