### ISSUE TITLE
ruby: Can't use gem from git master

### ISSUE THREAD

**Issue by jrochkind** [softdevteam/libkalibera#7]
I used to be able to use gem from git master, with `gem 'kalibera', github: "softdevteam/libkalibera"` in my Gemfile. But currently, if I try:

```
[!] There was an error while loading `kalibera.gemspec`: String can't be coerced into Float. Bundler cannot continue.

 #  from /Users/jrochkind/.gem/ruby/2.6.6/bundler/gems/libkalibera-70c95d537f54/ruby/kalibera.gemspec:7
 #  -------------------------------------------
 #    spec.name          = "kalibera"
 >    spec.version       = metadata["metadata"]["version"] + ".1"
 #    spec.authors       = ["Edd Barrett", "Carl Friedrich Bolz", "Chris Seaton"]
```

ruby 2.6.6p146, Bundler version 2.1.4, rubygems 3.0.3

**Comment by ltratt** [comment]
@chrisseaton Any ideas? I'm afraid I'm clueless about the Ruby aspects :/

**Comment by chrisseaton** [comment]
Yeah sorry PR attached fixes.

**Comment by chrisseaton** [comment]
@jrochkind can you report back if that works for you when you're ready?

**Comment by jrochkind** [comment]
yep, all good thanks @chrisseaton
